asef

diff --git a/.github/workflows/atlas-tests.yml b/.github/workflows/atlas-tests.yml
--- a/.github/workflows/atlas-tests.yml
+++ b/.github/workflows/atlas-tests.yml
@@ -45,7 +45,6 @@ env:
   BITCOIND_TEST: 1
   RUST_BACKTRACE: full
   SEGMENT_DOWNLOAD_TIMEOUT_MINS: 15
-  TEST_TIMEOUT: 30
 
 concurrency:
   # https://github.com/orgs/community/discussions/13496
@@ -96,111 +95,120 @@ jobs:
     steps:
       - name: CPU info
         run: |
-          echo ""
+          echo ""*************************""
           echo "CPU info:"
           cat /proc/cpuinfo
-          echo ""
+          echo ""*************************""
           echo "Memory:"
           free -m
-          echo ""
+          echo ""*************************""
           echo "Disk Type:"
           sudo lsblk -d -o name,rota
-          echo ""
+          echo ""*************************""
+          echo "cat /sys/block/sda/queue/rotational"
+          cat /sys/block/sda/queue/rotational
+          echo "*************************"
+          echo "cat /sys/block/sdb/queue/rotational"
+          cat /sys/block/sdb/queue/rotational
+          echo ""*************************""
           echo "mount -a:"
           sudo mount
           sudo df -h
+          echo ""*************************""
+          echo "ls /mnt"
+          sudo ls /mnt
 
-      - name: Checkout the latest code
-        id: git_checkout
-        uses: actions/checkout@v3
+      # - name: Checkout the latest code
+      #   id: git_checkout
+      #   uses: actions/checkout@v3
 
-      - name: Setup Rust Toolchain
-        id: setup_rust_toolchain
-        uses: actions-rust-lang/setup-rust-toolchain@v1
-        with:
-          toolchain: stable
-          components: llvm-tools-preview
-          cache: false
-
-      - name: Restore Cargo Cache
-        id: restore_cargo_cache
-        uses: actions/cache/restore@v3
-        with:
-          fail-on-cache-miss: true
-          path: |
-            ~/.cargo/bin/
-            ~/.cargo/registry/index/
-            ~/.cargo/registry/cache/
-            ~/.cargo/git/db/
-          key: ${{ github.event.repository.name }}-cargo
-          # key: ${{ github.event.repository.name }}-${{ github.sha }}-cargo
-
-      - name: Restore Bitcoin Binary Cache
-        id: restore_bitcoin_cache
-        uses: actions/cache/restore@v3
-        with:
-          fail-on-cache-miss: true
-          path: /tmp/bitcoin
-          key: ${{ github.event.repository.name }}-bitcoin-binaries
-
-      - name: Restore Test Archive Cache
-        id: restore_test-archive_cache
-        uses: actions/cache/restore@v3
-        with:
-          fail-on-cache-miss: true
-          path: /tmp/test_archive.tar.zst
-          key: ${{ github.event.repository.name }}-test-archive
-          # key: ${{ github.event.repository.name }}-${{ github.sha }}-test-archive
-
-      - name: Restore Target Cache
-        id: restore_target_cache
-        uses: actions/cache/restore@v3
-        with:
-          fail-on-cache-miss: true
-          path: ./target
-          key: ${{ github.event.repository.name }}-target
-          # key: ${{ github.event.repository.name }}-${{ github.sha }}-target
-
-      - name: Link Bitcoin Binary
-        id: bitcoin_binary
-        run: |
-          sudo ln -s /tmp/bitcoin/bin/bitcoind /bin/
-          ls -al /bin/bitcoind
-
-      - name: Run Tests
-        id: run_tests
-        timeout-minutes: ${{ env.TEST_TIMEOUT }}
-        run: |
-          cargo nextest run \
-            --test-threads 1 \
-            --run-ignored all \
-            --retries 2 \
-            --final-status-level fail \
-            --archive-file /tmp/test_archive.tar.zst \
-            "${{ matrix.test-name }}"
-
-      - name: Run grcov
-        id: run_grcov
-        run: |
-          grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info || exit 1
-
-      # - name: Code Coverage
-      #   id: code_coverage
-      #   uses: codecov/codecov-action@v3
+      # - name: Setup Rust Toolchain
+      #   id: setup_rust_toolchain
+      #   uses: actions-rust-lang/setup-rust-toolchain@v1
       #   with:
-      #     files: ./lcov.info
-      #     name: ${{ matrix.test-name }}
-      #     fail_ci_if_error: false
+      #     toolchain: stable
+      #     components: llvm-tools-preview
+      #     cache: false
 
-      - name: Upload Code Coverage
-        id: code_coverage
-        uses: Wandalen/wretry.action@master
-        with:
-          action: codecov/codecov-action@v3
-          with: |
-            files: ./lcov.info
-            name: ${{ matrix.test-name }}
-            fail_ci_if_error: false
-            verbose: true
-          attempt_limit: 3
-          attempt_delay: 10000
+      # - name: Restore Cargo Cache
+      #   id: restore_cargo_cache
+      #   uses: actions/cache/restore@v3
+      #   with:
+      #     fail-on-cache-miss: true
+      #     path: |
+      #       ~/.cargo/bin/
+      #       ~/.cargo/registry/index/
+      #       ~/.cargo/registry/cache/
+      #       ~/.cargo/git/db/
+      #     key: ${{ github.event.repository.name }}-cargo
+      #     # key: ${{ github.event.repository.name }}-${{ github.sha }}-cargo
+
+      # - name: Restore Bitcoin Binary Cache
+      #   id: restore_bitcoin_cache
+      #   uses: actions/cache/restore@v3
+      #   with:
+      #     fail-on-cache-miss: true
+      #     path: /tmp/bitcoin
+      #     key: ${{ github.event.repository.name }}-bitcoin-binaries
+
+      # - name: Restore Test Archive Cache
+      #   id: restore_test-archive_cache
+      #   uses: actions/cache/restore@v3
+      #   with:
+      #     fail-on-cache-miss: true
+      #     path: /tmp/test_archive.tar.zst
+      #     key: ${{ github.event.repository.name }}-test-archive
+      #     # key: ${{ github.event.repository.name }}-${{ github.sha }}-test-archive
+
+      # - name: Restore Target Cache
+      #   id: restore_target_cache
+      #   uses: actions/cache/restore@v3
+      #   with:
+      #     fail-on-cache-miss: true
+      #     path: ./target
+      #     key: ${{ github.event.repository.name }}-target
+      #     # key: ${{ github.event.repository.name }}-${{ github.sha }}-target
+
+      # - name: Link Bitcoin Binary
+      #   id: bitcoin_binary
+      #   run: |
+      #     sudo ln -s /tmp/bitcoin/bin/bitcoind /bin/
+      #     ls -al /bin/bitcoind
+
+      # - name: Run Tests
+      #   id: run_tests
+      #   timeout-minutes: 30
+      #   run: |
+      #     cargo nextest run \
+      #       --test-threads 1 \
+      #       --run-ignored all \
+      #       --retries 2 \
+      #       --final-status-level fail \
+      #       --archive-file /tmp/test_archive.tar.zst \
+      #       "${{ matrix.test-name }}"
+
+      # - name: Run grcov
+      #   id: run_grcov
+      #   run: |
+      #     grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info || exit 1
+
+      # # - name: Code Coverage
+      # #   id: code_coverage
+      # #   uses: codecov/codecov-action@v3
+      # #   with:
+      # #     files: ./lcov.info
+      # #     name: ${{ matrix.test-name }}
+      # #     fail_ci_if_error: false
+
+      # - name: Upload Code Coverage
+      #   id: code_coverage
+      #   uses: Wandalen/wretry.action@master
+      #   with:
+      #     action: codecov/codecov-action@v3
+      #     with: |
+      #       files: ./lcov.info
+      #       name: ${{ matrix.test-name }}
+      #       fail_ci_if_error: false
+      #       verbose: true
+      #     attempt_limit: 3
+      #     attempt_delay: 10000
