testing exclusion

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -127,129 +127,129 @@ jobs:
           BRANCH: ${{ github.ref_name }}
         run: bash ./.github/scripts/check_release.sh
 
-  ## --- Create a reusable cache for tests ------------------------------------
-  create-cache:
-    name: Create Test Cache
-    needs:
-      - rustfmt
-      - changelog-check
-      - check-release
-    if: >-
-      !cancelled() &&
-      needs.rustfmt.result == 'success' &&
-      (needs.check-release.outputs.is_node_release == 'true' ||
-      needs.check-release.outputs.is_signer_release == 'true' ||
-      github.event_name == 'workflow_dispatch' ||
-      github.event_name == 'pull_request' ||
-      github.event_name == 'merge_group')
-    uses: ./.github/workflows/create-cache.yml
+  # ## --- Create a reusable cache for tests ------------------------------------
+  # create-cache:
+  #   name: Create Test Cache
+  #   needs:
+  #     - rustfmt
+  #     - changelog-check
+  #     - check-release
+  #   if: >-
+  #     !cancelled() &&
+  #     needs.rustfmt.result == 'success' &&
+  #     (needs.check-release.outputs.is_node_release == 'true' ||
+  #     needs.check-release.outputs.is_signer_release == 'true' ||
+  #     github.event_name == 'workflow_dispatch' ||
+  #     github.event_name == 'pull_request' ||
+  #     github.event_name == 'merge_group')
+  #   uses: ./.github/workflows/create-cache.yml
 
-  ## --- Run stacks core tests ------------------------------------------------
-  stacks-core-tests:
-    name: Stacks Core Tests
-    needs:
-      - rustfmt
-      - changelog-check
-      - create-cache
-      - check-release
-    if: >-
-      !cancelled() &&
-      needs.rustfmt.result == 'success' &&
-      (needs.check-release.outputs.is_node_release == 'true' ||
-      needs.check-release.outputs.is_signer_release == 'true' ||
-      github.event_name == 'workflow_dispatch' ||
-      github.event_name == 'pull_request' ||
-      github.event_name == 'merge_group')
-    uses: ./.github/workflows/stacks-core-tests.yml
+  # ## --- Run stacks core tests ------------------------------------------------
+  # stacks-core-tests:
+  #   name: Stacks Core Tests
+  #   needs:
+  #     - rustfmt
+  #     - changelog-check
+  #     - create-cache
+  #     - check-release
+  #   if: >-
+  #     !cancelled() &&
+  #     needs.rustfmt.result == 'success' &&
+  #     (needs.check-release.outputs.is_node_release == 'true' ||
+  #     needs.check-release.outputs.is_signer_release == 'true' ||
+  #     github.event_name == 'workflow_dispatch' ||
+  #     github.event_name == 'pull_request' ||
+  #     github.event_name == 'merge_group')
+  #   uses: ./.github/workflows/stacks-core-tests.yml
 
-  ## --- Run bitcoin Tests ----------------------------------------------------
-  bitcoin-tests:
-    name: Bitcoin Tests
-    needs:
-      - rustfmt
-      - changelog-check
-      - create-cache
-      - check-release
-    if: >-
-      !cancelled() &&
-      needs.rustfmt.result == 'success' &&
-      (needs.check-release.outputs.is_node_release == 'true' ||
-      needs.check-release.outputs.is_signer_release == 'true' ||
-      github.event_name == 'workflow_dispatch' ||
-      github.event_name == 'pull_request' ||
-      github.event_name == 'merge_group')
-    uses: ./.github/workflows/bitcoin-tests.yml
+  # ## --- Run bitcoin Tests ----------------------------------------------------
+  # bitcoin-tests:
+  #   name: Bitcoin Tests
+  #   needs:
+  #     - rustfmt
+  #     - changelog-check
+  #     - create-cache
+  #     - check-release
+  #   if: >-
+  #     !cancelled() &&
+  #     needs.rustfmt.result == 'success' &&
+  #     (needs.check-release.outputs.is_node_release == 'true' ||
+  #     needs.check-release.outputs.is_signer_release == 'true' ||
+  #     github.event_name == 'workflow_dispatch' ||
+  #     github.event_name == 'pull_request' ||
+  #     github.event_name == 'merge_group')
+  #   uses: ./.github/workflows/bitcoin-tests.yml
 
-  ## --- Run bitcoin RPC Tests ------------------------------------------------
-  bitcoin-rpc-tests:
-    name: Bitcoin RPC Tests
-    needs:
-      - rustfmt
-      - create-cache
-      - check-release
-    if: >-
-      !cancelled() &&
-      needs.rustfmt.result == 'success' &&
-      (needs.check-release.outputs.is_node_release == 'true' ||
-      needs.check-release.outputs.is_signer_release == 'true' ||
-      github.event_name == 'workflow_dispatch' ||
-      github.event_name == 'pull_request' ||
-      github.event_name == 'merge_group')
-    uses: ./.github/workflows/bitcoin-rpc-tests.yml
+  # ## --- Run bitcoin RPC Tests ------------------------------------------------
+  # bitcoin-rpc-tests:
+  #   name: Bitcoin RPC Tests
+  #   needs:
+  #     - rustfmt
+  #     - create-cache
+  #     - check-release
+  #   if: >-
+  #     !cancelled() &&
+  #     needs.rustfmt.result == 'success' &&
+  #     (needs.check-release.outputs.is_node_release == 'true' ||
+  #     needs.check-release.outputs.is_signer_release == 'true' ||
+  #     github.event_name == 'workflow_dispatch' ||
+  #     github.event_name == 'pull_request' ||
+  #     github.event_name == 'merge_group')
+  #   uses: ./.github/workflows/bitcoin-rpc-tests.yml
 
-  ## --- Run P2P Tests --------------------------------------------------------
-  p2p-tests:
-    name: P2P Tests
-    needs:
-      - rustfmt
-      - changelog-check
-      - create-cache
-      - check-release
-    if: >-
-      !cancelled() &&
-      needs.rustfmt.result == 'success' &&
-      (needs.check-release.outputs.is_node_release == 'true' ||
-      needs.check-release.outputs.is_signer_release == 'true' ||
-      github.event_name == 'workflow_dispatch' ||
-      github.event_name == 'pull_request' ||
-      github.event_name == 'merge_group')
-    uses: ./.github/workflows/p2p-tests.yml
+  # ## --- Run P2P Tests --------------------------------------------------------
+  # p2p-tests:
+  #   name: P2P Tests
+  #   needs:
+  #     - rustfmt
+  #     - changelog-check
+  #     - create-cache
+  #     - check-release
+  #   if: >-
+  #     !cancelled() &&
+  #     needs.rustfmt.result == 'success' &&
+  #     (needs.check-release.outputs.is_node_release == 'true' ||
+  #     needs.check-release.outputs.is_signer_release == 'true' ||
+  #     github.event_name == 'workflow_dispatch' ||
+  #     github.event_name == 'pull_request' ||
+  #     github.event_name == 'merge_group')
+  #   uses: ./.github/workflows/p2p-tests.yml
 
-  ## --- Jobs to run on PR or manual trigger ----------------------------------
-  # Runs when:
-  #     - this workflow is called manually
-  #     - PR is opened or new commits pushed
-  #     - PR added to merge queue
-  #
-  ## --- Cargo Hack check------------------------------------------------------
-  cargo-hack-check:
-    name: Cargo Hack Check
-    needs:
-      - rustfmt
-      - changelog-check
-      - check-release
-    if: >-
-      !cancelled() &&
-      needs.rustfmt.result == 'success' &&
-      (github.event_name == 'workflow_dispatch' ||
-      github.event_name == 'pull_request' ||
-      github.event_name == 'merge_group')
-    uses: ./.github/workflows/cargo-hack-check.yml
+  # ## --- Jobs to run on PR or manual trigger ----------------------------------
+  # # Runs when:
+  # #     - this workflow is called manually
+  # #     - PR is opened or new commits pushed
+  # #     - PR added to merge queue
+  # #
+  # ## --- Cargo Hack check------------------------------------------------------
+  # cargo-hack-check:
+  #   name: Cargo Hack Check
+  #   needs:
+  #     - rustfmt
+  #     - changelog-check
+  #     - check-release
+  #   if: >-
+  #     !cancelled() &&
+  #     needs.rustfmt.result == 'success' &&
+  #     (github.event_name == 'workflow_dispatch' ||
+  #     github.event_name == 'pull_request' ||
+  #     github.event_name == 'merge_group')
+  #   uses: ./.github/workflows/cargo-hack-check.yml
 
-  ## --- Validate constants dumped by stacks-inspect --------------------------
-  constants-check:
-    name: Constants Check
-    needs:
-      - rustfmt
-      - changelog-check
-      - check-release
-    if: >-
-      !cancelled() &&
-      needs.rustfmt.result == 'success' &&
-      (github.event_name == 'workflow_dispatch' ||
-      github.event_name == 'pull_request' ||
-      github.event_name == 'merge_group')
-    uses: ./.github/workflows/constants-check.yml
+  # ## --- Validate constants dumped by stacks-inspect --------------------------
+  # constants-check:
+  #   name: Constants Check
+  #   needs:
+  #     - rustfmt
+  #     - changelog-check
+  #     - check-release
+  #   if: >-
+  #     !cancelled() &&
+  #     needs.rustfmt.result == 'success' &&
+  #     (github.event_name == 'workflow_dispatch' ||
+  #     github.event_name == 'pull_request' ||
+  #     github.event_name == 'merge_group')
+  #   uses: ./.github/workflows/constants-check.yml
 
   ## --- Jobs to run on release trigger ---------------------------------------
   # Runs when:
@@ -283,90 +283,90 @@ jobs:
       signer_tag: ${{ needs.check-release.outputs.signer_tag }} # 6 place version format like 1.2.3.4.5.6
       is_node_release: ${{ needs.check-release.outputs.is_node_release }} # boolean used in matrix conditional in .github/workflows/release-github.yml
 
-  ## --- Epoch Tests ----------------------------------------------------------
-  epoch-tests:
-    name: Epoch Tests
-    needs:
-      - rustfmt
-      - changelog-check
-      - create-cache
-      - check-release
-    if: >-
-      !cancelled() &&
-      needs.rustfmt.result == 'success' &&
-      (needs.check-release.outputs.is_node_release == 'true' ||
-      needs.check-release.outputs.is_signer_release == 'true')
-    uses: ./.github/workflows/epoch-tests.yml
+  # ## --- Epoch Tests ----------------------------------------------------------
+  # epoch-tests:
+  #   name: Epoch Tests
+  #   needs:
+  #     - rustfmt
+  #     - changelog-check
+  #     - create-cache
+  #     - check-release
+  #   if: >-
+  #     !cancelled() &&
+  #     needs.rustfmt.result == 'success' &&
+  #     (needs.check-release.outputs.is_node_release == 'true' ||
+  #     needs.check-release.outputs.is_signer_release == 'true')
+  #   uses: ./.github/workflows/epoch-tests.yml
 
-  ## --- Code Coverage --------------------------------------------------------
-  # Merge and upload code coverage report files once all tests are done
-  #
-  # Runs when:
-  #   - always (unless workflow is cancelled OR any of bitcoin or stacks-core or p2p tests are skipped)
-  trigger-code-coverage-report:
-    if: >-
-      always() &&
-      !cancelled() &&
-      github.event.repository.visibility == 'public' &&
-      !contains(needs.stacks-core-tests.result, 'skipped') &&
-      !contains(needs.bitcoin-tests.result, 'skipped') &&
-      !contains(needs.p2p-tests.result, 'skipped')
-    name: Merge & Upload Code Coverage Report
-    runs-on: ubuntu-latest
-    needs:
-      - stacks-core-tests
-      - bitcoin-tests
-      - p2p-tests
-    env:
-      REPORT_FILES_DIR: "code_coverage_files"
-      REPORT_FILES_EXT: "info"
-    steps:
-      # Checkout the code (Coveralls requires source code to be available when action is called)
-      - name: Checkout the latest code
-        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
-        with:
-          ref: ${{ github.event.pull_request.head.sha || github.ref }}
+  # ## --- Code Coverage --------------------------------------------------------
+  # # Merge and upload code coverage report files once all tests are done
+  # #
+  # # Runs when:
+  # #   - always (unless workflow is cancelled OR any of bitcoin or stacks-core or p2p tests are skipped)
+  # trigger-code-coverage-report:
+  #   if: >-
+  #     always() &&
+  #     !cancelled() &&
+  #     github.event.repository.visibility == 'public' &&
+  #     !contains(needs.stacks-core-tests.result, 'skipped') &&
+  #     !contains(needs.bitcoin-tests.result, 'skipped') &&
+  #     !contains(needs.p2p-tests.result, 'skipped')
+  #   name: Merge & Upload Code Coverage Report
+  #   runs-on: ubuntu-latest
+  #   needs:
+  #     - stacks-core-tests
+  #     - bitcoin-tests
+  #     - p2p-tests
+  #   env:
+  #     REPORT_FILES_DIR: "code_coverage_files"
+  #     REPORT_FILES_EXT: "info"
+  #   steps:
+  #     # Checkout the code (Coveralls requires source code to be available when action is called)
+  #     - name: Checkout the latest code
+  #       uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
+  #       with:
+  #         ref: ${{ github.event.pull_request.head.sha || github.ref }}
 
-      # Download the code coverage .info files generated by tests from artifacts (prefixed by commit SHA)
-      - name: Download code coverage artifacts
-        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # 8.0.1
-        with:
-          pattern: ${{ github.sha }}-*.${{ env.REPORT_FILES_EXT }}
-          path: ${{ env.REPORT_FILES_DIR }}
-          merge-multiple: true
+  #     # Download the code coverage .info files generated by tests from artifacts (prefixed by commit SHA)
+  #     - name: Download code coverage artifacts
+  #       uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # 8.0.1
+  #       with:
+  #         pattern: ${{ github.sha }}-*.${{ env.REPORT_FILES_EXT }}
+  #         path: ${{ env.REPORT_FILES_DIR }}
+  #         merge-multiple: true
 
-      # Check for at least 1 code coverage files
-      - name: Check for at least 1 code coverage file
-        run: |
-          file_count=$(find -type f -wholename "./${{ env.REPORT_FILES_DIR }}/*.${{ env.REPORT_FILES_EXT }}" | wc -l)
-          if [ "$file_count" -eq 0 ]; then
-            echo "ERROR: no code coverage files found to merge. Verify that they were correctly generated and uploaded in prior CI steps"
-            exit 1
-          fi
+  #     # Check for at least 1 code coverage files
+  #     - name: Check for at least 1 code coverage file
+  #       run: |
+  #         file_count=$(find -type f -wholename "./${{ env.REPORT_FILES_DIR }}/*.${{ env.REPORT_FILES_EXT }}" | wc -l)
+  #         if [ "$file_count" -eq 0 ]; then
+  #           echo "ERROR: no code coverage files found to merge. Verify that they were correctly generated and uploaded in prior CI steps"
+  #           exit 1
+  #         fi
 
-      # Install lcov for merging the reports
-      - name: Install lcov
-        run: |
-          sudo apt-get install -y --no-install-recommends lcov
+  #     # Install lcov for merging the reports
+  #     - name: Install lcov
+  #       run: |
+  #         sudo apt-get install -y --no-install-recommends lcov
 
-      # Merge n coverage report files into 1 file using lcov
-      - name: Merge code coverage files
-        run: |
-          cd "${{ env.REPORT_FILES_DIR }}" || exit 1
-          args=()
-          # Build the full -a <file> argument list in a single shell invocation, using NUL delimiters
-          # The use of xargs can batch operations when len of arguments exceeds ARG_MAX, which could overwrite the report file
-          while IFS= read -r -d '' file; do
-            args+=(-a "$file")
-          done < <(find . -type f -name "*.${{ env.REPORT_FILES_EXT }}" -print0)
-          lcov "${args[@]}" -o "code-coverage-report.${{ env.REPORT_FILES_EXT }}"
-          cd ..
+  #     # Merge n coverage report files into 1 file using lcov
+  #     - name: Merge code coverage files
+  #       run: |
+  #         cd "${{ env.REPORT_FILES_DIR }}" || exit 1
+  #         args=()
+  #         # Build the full -a <file> argument list in a single shell invocation, using NUL delimiters
+  #         # The use of xargs can batch operations when len of arguments exceeds ARG_MAX, which could overwrite the report file
+  #         while IFS= read -r -d '' file; do
+  #           args+=(-a "$file")
+  #         done < <(find . -type f -name "*.${{ env.REPORT_FILES_EXT }}" -print0)
+  #         lcov "${args[@]}" -o "code-coverage-report.${{ env.REPORT_FILES_EXT }}"
+  #         cd ..
 
-      # Upload the merged code coverage file to Coveralls
-      - name: Upload code coverage to Coveralls
-        uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # v2.3.6
-        with:
-          file: ${{ env.REPORT_FILES_DIR }}/code-coverage-report.${{ env.REPORT_FILES_EXT }}
-          compare-ref: ${{ github.base_ref }} # defaults to master if this isn't supplied
-          build-number: ${{ github.run_id }}-${{ github.run_attempt }} # include run attempt in build so that repeated CI job runs don't cause a "job already closed" error on upload
-          fail-on-error: true
+  #     # Upload the merged code coverage file to Coveralls
+  #     - name: Upload code coverage to Coveralls
+  #       uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # v2.3.6
+  #       with:
+  #         file: ${{ env.REPORT_FILES_DIR }}/code-coverage-report.${{ env.REPORT_FILES_EXT }}
+  #         compare-ref: ${{ github.base_ref }} # defaults to master if this isn't supplied
+  #         build-number: ${{ github.run_id }}-${{ github.run_attempt }} # include run attempt in build so that repeated CI job runs don't cause a "job already closed" error on upload
+  #         fail-on-error: true
