fix conditionals

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -174,220 +174,225 @@ jobs:
         run: |
           echo "is_node_release:   ${{ needs.check-release.outputs.is_node_release }}"
           echo "is_signer_release: ${{ needs.check-release.outputs.is_signer_release }}"
-  # ## Create a reusable cache for tests
+  ## Create a reusable cache for tests
+  ##
+  ## Runs when:
+  ##   - it is a node release run
+  ##   or any of:
+  ##     - this workflow is called manually
+  ##     - PR is opened
+  ##     - PR added to merge queue
+  create-cache:
+    name: Create Test Cache
+    needs:
+      - rustfmt
+      - changelog-check
+      - check-release
+    if: always() && !cancelled()
+    # if: >-
+    #   needs.check-release.outputs.is_node_release == 'true' ||
+    #   needs.check-release.outputs.is_signer_release == 'true' ||
+    #   github.event_name == 'workflow_dispatch' ||
+    #   github.event_name == 'pull_request' ||
+    #   github.event_name == 'merge_group'
+    uses: ./.github/workflows/create-cache.yml
+
+  ## Tests to run regularly
+  ##
+  ## Runs when:
+  ##   - it is a node or signer-only release run
+  ##   or any of:
+  ##     - this workflow is called manually
+  ##     - PR is opened
+  ##     - PR added to merge queue
+  stacks-core-tests:
+    name: Stacks Core Tests
+    needs:
+      - rustfmt
+      - changelog-check
+      - create-cache
+      - check-release
+    if: >-
+      # needs.check-release.outputs.is_node_release == 'true' ||
+      # needs.check-release.outputs.is_signer_release == 'true' ||
+      github.event_name == 'workflow_dispatch' ||
+      github.event_name == 'pull_request' ||
+      github.event_name == 'merge_group'
+    uses: ./.github/workflows/stacks-core-tests.yml
+
+  ## Validate constants dumped by stacks-inspect
+  ##
+  ## Runs when:
+  ##   - it is a node or signer-only release run
+  ##   or any of:
+  ##     - this workflow is called manually
+  ##     - PR is opened
+  ##     - PR added to merge queue
+  constants-check:
+    name: Constants Check
+    needs:
+      - rustfmt
+      - changelog-check
+      - check-release
+    if: >-
+      # needs.check-release.outputs.is_node_release == 'true' ||
+      # needs.check-release.outputs.is_signer_release == 'true' ||
+      github.event_name == 'workflow_dispatch' ||
+      github.event_name == 'pull_request' ||
+      github.event_name == 'merge_group'
+    uses: ./.github/workflows/constants-check.yml
+
+  ## Checks to run on built binaries
+  ##
+  ## Runs when:
+  ##   - it is a node or signer-only release run
+  ##   or any of:
+  ##     - this workflow is called manually
+  ##     - PR is opened
+  ##     - PR added to merge queue
+  cargo-hack-check:
+    name: Cargo Hack Check
+    needs:
+      - rustfmt
+      - changelog-check
+      - check-release
+    if: >-
+      # needs.check-release.outputs.is_node_release == 'true' ||
+      # needs.check-release.outputs.is_signer_release == 'true' ||
+      github.event_name == 'workflow_dispatch' ||
+      github.event_name == 'pull_request' ||
+      github.event_name == 'merge_group'
+    uses: ./.github/workflows/cargo-hack-check.yml
+
+  ## Checks to run on built binaries
+  ##
+  ## Runs when:
+  ##   - it is a node release run
+  ##   or any of:
+  ##     - this workflow is called manually
+  ##     - PR is opened
+  ##     - PR added to merge queue
+  bitcoin-tests:
+    name: Bitcoin Tests
+    needs:
+      - rustfmt
+      - changelog-check
+      - create-cache
+      - check-release
+    if: >-
+      # needs.check-release.outputs.is_node_release == 'true' ||
+      # needs.check-release.outputs.is_signer_release == 'true' ||
+      github.event_name == 'workflow_dispatch' ||
+      github.event_name == 'pull_request' ||
+      github.event_name == 'merge_group'
+    uses: ./.github/workflows/bitcoin-tests.yml
+
+  ## Checks to run on built binaries
+  ##
+  ## Runs when:
+  ##   - it is a node release run
+  ##   or any of:
+  ##     - this workflow is called manually
+  ##     - PR is opened
+  ##     - PR added to merge queue
+  bitcoin-rpc-tests:
+    name: Bitcoin RPC Tests
+    needs:
+      - rustfmt
+      - create-cache
+      - check-release
+    if: >-
+      # needs.check-release.outputs.is_node_release == 'true' ||
+      github.event_name == 'workflow_dispatch' ||
+      github.event_name == 'pull_request' ||
+      github.event_name == 'merge_group'
+    uses: ./.github/workflows/bitcoin-rpc-tests.yml
+
+  p2p-tests:
+    name: P2P Tests
+    needs:
+      - rustfmt
+      - changelog-check
+      - create-cache
+      - check-release
+    if: >-
+      # needs.check-release.outputs.is_node_release == 'true' ||
+      github.event_name == 'workflow_dispatch' ||
+      github.event_name == 'pull_request' ||
+      github.event_name == 'merge_group'
+    uses: ./.github/workflows/p2p-tests.yml
+
+  ## Test to run on a tagged release
+  ##
+  ## Runs when:
+  ##   - it is a node release run
+  epoch-tests:
+    name: Epoch Tests
+    needs:
+      - rustfmt
+      - changelog-check
+      - create-cache
+      - check-release
+    if: >-
+      needs.check-release.outputs.is_node_release == 'true' ||
+      needs.check-release.outputs.is_signer_release == 'true' ||
+    uses: ./.github/workflows/epoch-tests.yml
+
+  # ## Merge and upload code coverage report files once all tests are done
   # ##
   # ## Runs when:
-  # ##   - it is a node release run
-  # ##   or any of:
-  # ##     - this workflow is called manually
-  # ##     - PR is opened
-  # ##     - PR added to merge queue
-  # create-cache:
-  #   name: Create Test Cache
+  # ##   - always (unless workflow is cancelled OR either bitcoin or stacks-core tests are skipped)
+  # trigger-code-coverage-report:
+  #   if: always() && !cancelled() && !contains(needs.stacks-core-tests.result, 'skipped') && !contains(needs.bitcoin-tests.result, 'skipped')
+  #   name: Merge & Upload Code Coverage Report
+  #   runs-on: ubuntu-latest
   #   needs:
-  #     - rustfmt
-  #     - changelog-check
-  #     # - check-release
-  #   if: |
-  #     needs.check-release.outputs.is_node_release == 'true' ||
-  #     github.event_name == 'workflow_dispatch' ||
-  #     github.event_name == 'pull_request' ||
-  #     github.event_name == 'merge_group'
-  #   uses: ./.github/workflows/create-cache.yml
-
-  # ## Tests to run regularly
-  # ##
-  # ## Runs when:
-  # ##   - it is a node or signer-only release run
-  # ##   or any of:
-  # ##     - this workflow is called manually
-  # ##     - PR is opened
-  # ##     - PR added to merge queue
-  # stacks-core-tests:
-  #   name: Stacks Core Tests
-  #   needs:
-  #     - rustfmt
-  #     - changelog-check
-  #     - create-cache
-  # #     - check-release
-  #   if: |
-  #     needs.check-release.outputs.is_node_release == 'true' ||
-  #     needs.check-release.outputs.is_signer_release == 'true' ||
-  #     github.event_name == 'workflow_dispatch' ||
-  #     github.event_name == 'pull_request' ||
-  #     github.event_name == 'merge_group'
-  #   uses: ./.github/workflows/stacks-core-tests.yml
-
-  # ## Validate constants dumped by stacks-inspect
-  # ##
-  # ## Runs when:
-  # ##   - it is a node or signer-only release run
-  # ##   or any of:
-  # ##     - this workflow is called manually
-  # ##     - PR is opened
-  # ##     - PR added to merge queue
-  # constants-check:
-  #   name: Constants Check
-  #   needs:
-  #     - rustfmt
-  #     - changelog-check
-  # #     - check-release
-  #   if: |
-  #     needs.check-release.outputs.is_node_release == 'true' ||
-  #     needs.check-release.outputs.is_signer_release == 'true' ||
-  #     github.event_name == 'workflow_dispatch' ||
-  #     github.event_name == 'pull_request' ||
-  #     github.event_name == 'merge_group'
-  #   uses: ./.github/workflows/constants-check.yml
-
-  # ## Checks to run on built binaries
-  # ##
-  # ## Runs when:
-  # ##   - it is a node or signer-only release run
-  # ##   or any of:
-  # ##     - this workflow is called manually
-  # ##     - PR is opened
-  # ##     - PR added to merge queue
-  # cargo-hack-check:
-  #   name: Cargo Hack Check
-  #   needs:
-  #     - rustfmt
-  #     - changelog-check
-  # #     - check-release
-  #   if: |
-  #     needs.check-release.outputs.is_node_release == 'true' ||
-  #     needs.check-release.outputs.is_signer_release == 'true' ||
-  #     github.event_name == 'workflow_dispatch' ||
-  #     github.event_name == 'pull_request' ||
-  #     github.event_name == 'merge_group'
-  #   uses: ./.github/workflows/cargo-hack-check.yml
-
-  # ## Checks to run on built binaries
-  # ##
-  # ## Runs when:
-  # ##   - it is a node release run
-  # ##   or any of:
-  # ##     - this workflow is called manually
-  # ##     - PR is opened
-  # ##     - PR added to merge queue
-  # bitcoin-tests:
-  #   name: Bitcoin Tests
-  #   needs:
-  #     - rustfmt
-  #     - changelog-check
-  #     - create-cache
-  # #     - check-release
-  #   if: |
-  #     needs.check-release.outputs.is_node_release == 'true' ||
-  #     github.event_name == 'workflow_dispatch' ||
-  #     github.event_name == 'pull_request' ||
-  #     github.event_name == 'merge_group'
-  #   uses: ./.github/workflows/bitcoin-tests.yml
-
-  # ## Checks to run on built binaries
-  # ##
-  # ## Runs when:
-  # ##   - it is a node release run
-  # ##   or any of:
-  # ##     - this workflow is called manually
-  # ##     - PR is opened
-  # ##     - PR added to merge queue
-  # bitcoin-rpc-tests:
-  #   name: Bitcoin RPC Tests
-  #   needs:
-  #     - rustfmt
-  #     - create-cache
-  # #     - check-release
-  #   if: |
-  #     needs.check-release.outputs.is_node_release == 'true' ||
-  #     github.event_name == 'workflow_dispatch' ||
-  #     github.event_name == 'pull_request' ||
-  #     github.event_name == 'merge_group'
-  #   uses: ./.github/workflows/bitcoin-rpc-tests.yml
-
-  # p2p-tests:
-  #   name: P2P Tests
-  #   needs:
-  #     - rustfmt
-  #     - changelog-check
-  #     - create-cache
-  # #     - check-release
-  #   if: |
-  #     needs.check-release.outputs.is_node_release == 'true' ||
-  #     github.event_name == 'workflow_dispatch' ||
-  #     github.event_name == 'pull_request' ||
-  #     github.event_name == 'merge_group'
-  #   uses: ./.github/workflows/p2p-tests.yml
-
-  # ## Test to run on a tagged release
-  # ##
-  # ## Runs when:
-  # ##   - it is a node release run
-  # epoch-tests:
-  #   name: Epoch Tests
-  #   needs:
-  #     - rustfmt
-  #     - changelog-check
-  #     - create-cache
-  #     # - check-release
-  #   if: needs.check-release.outputs.is_node_release == 'true'
-  #   uses: ./.github/workflows/epoch-tests.yml
-
-  # # ## Merge and upload code coverage report files once all tests are done
-  # # ##
-  # # ## Runs when:
-  # # ##   - always (unless workflow is cancelled OR either bitcoin or stacks-core tests are skipped)
-  # # trigger-code-coverage-report:
-  # #   if: always() && !cancelled() && !contains(needs.stacks-core-tests.result, 'skipped') && !contains(needs.bitcoin-tests.result, 'skipped')
-  # #   name: Merge & Upload Code Coverage Report
-  # #   runs-on: ubuntu-latest
-  # #   needs:
-  # #     - stacks-core-tests
-  # #     - bitcoin-tests
-  # #     - p2p-tests
-  # #     - epoch-tests
-  # #   env:
-  # #     REPORT_FILES_DIR: "code_coverage_files"
-  # #     REPORT_FILES_EXT: "info"
-  # #   steps:
-  # #     # Checkout the code (Coveralls requires source code to be available when action is called)
-  # #     - name: Checkout the latest code
-  # #       uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
-  # #     # Download the code coverage .info files generated by tests from artifacts (prefixed by commit SHA)
-  # #     - name: Download code coverage artifacts
-  # #       uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # 8.0.1
-  # #       with:
-  # #         pattern: ${{ github.sha }}-*.${{ env.REPORT_FILES_EXT }}
-  # #         path: ${{ env.REPORT_FILES_DIR }}
-  # #         merge-multiple: true
-  # #     # Check for at least 1 code coverage files
-  # #     - name: Check for at least 1 code coverage file
-  # #       run: |
-  # #         file_count=$(find -type f -wholename "./${{ env.REPORT_FILES_DIR }}/*.${{ env.REPORT_FILES_EXT }}" | wc -l)
-  # #         if [ "$file_count" -eq 0 ]; then
-  # #           echo "ERROR: no code coverage files found to merge. Verify that they were correctly generated and uploaded in prior CI steps"
-  # #           exit 1
-  # #         fi
-  # #     # Install lcov for merging the reports
-  # #     - name: Install lcov
-  # #       run: |
-  # #         sudo apt-get install -y --no-install-recommends lcov
-  # #     # Merge n coverage report files into 1 file using lcov
-  # #     - name: Merge code coverage files
-  # #       run: |
-  # #         cd "${{ env.REPORT_FILES_DIR }}" || exit 1
-  # #         args=()
-  # #         # Build the full -a <file> argument list in a single shell invocation, using NUL delimiters
-  # #         # The use of xargs can batch operations when len of arguments exceeds ARG_MAX, which could overwrite the report file
-  # #         while IFS= read -r -d '' file; do
-  # #           args+=(-a "$file")
-  # #         done < <(find . -type f -name "*.${{ env.REPORT_FILES_EXT }}" -print0)
-  # #         lcov "${args[@]}" -o "code-coverage-report.${{ env.REPORT_FILES_EXT }}"
-  # #         cd ..
-  # #     # Upload the merged code coverage file to Coveralls
-  # #     - name: Upload code coverage to Coveralls
-  # #       uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # v2.3.6
-  # #       with:
-  # #         file: ${{ env.REPORT_FILES_DIR }}/code-coverage-report.${{ env.REPORT_FILES_EXT }}
-  # #         compare-ref: ${{ github.base_ref }} # defaults to master if this isn't supplied
-  # #         fail-on-error: true
+  #     - stacks-core-tests
+  #     - bitcoin-tests
+  #     - p2p-tests
+  #     - epoch-tests
+  #   env:
+  #     REPORT_FILES_DIR: "code_coverage_files"
+  #     REPORT_FILES_EXT: "info"
+  #   steps:
+  #     # Checkout the code (Coveralls requires source code to be available when action is called)
+  #     - name: Checkout the latest code
+  #       uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
+  #     # Download the code coverage .info files generated by tests from artifacts (prefixed by commit SHA)
+  #     - name: Download code coverage artifacts
+  #       uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # 8.0.1
+  #       with:
+  #         pattern: ${{ github.sha }}-*.${{ env.REPORT_FILES_EXT }}
+  #         path: ${{ env.REPORT_FILES_DIR }}
+  #         merge-multiple: true
+  #     # Check for at least 1 code coverage files
+  #     - name: Check for at least 1 code coverage file
+  #       run: |
+  #         file_count=$(find -type f -wholename "./${{ env.REPORT_FILES_DIR }}/*.${{ env.REPORT_FILES_EXT }}" | wc -l)
+  #         if [ "$file_count" -eq 0 ]; then
+  #           echo "ERROR: no code coverage files found to merge. Verify that they were correctly generated and uploaded in prior CI steps"
+  #           exit 1
+  #         fi
+  #     # Install lcov for merging the reports
+  #     - name: Install lcov
+  #       run: |
+  #         sudo apt-get install -y --no-install-recommends lcov
+  #     # Merge n coverage report files into 1 file using lcov
+  #     - name: Merge code coverage files
+  #       run: |
+  #         cd "${{ env.REPORT_FILES_DIR }}" || exit 1
+  #         args=()
+  #         # Build the full -a <file> argument list in a single shell invocation, using NUL delimiters
+  #         # The use of xargs can batch operations when len of arguments exceeds ARG_MAX, which could overwrite the report file
+  #         while IFS= read -r -d '' file; do
+  #           args+=(-a "$file")
+  #         done < <(find . -type f -name "*.${{ env.REPORT_FILES_EXT }}" -print0)
+  #         lcov "${args[@]}" -o "code-coverage-report.${{ env.REPORT_FILES_EXT }}"
+  #         cd ..
+  #     # Upload the merged code coverage file to Coveralls
+  #     - name: Upload code coverage to Coveralls
+  #       uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # v2.3.6
+  #       with:
+  #         file: ${{ env.REPORT_FILES_DIR }}/code-coverage-report.${{ env.REPORT_FILES_EXT }}
+  #         compare-ref: ${{ github.base_ref }} # defaults to master if this isn't supplied
+  #         fail-on-error: true
