full test

diff --git a/.github/workflows/image-build-source.yml b/.github/workflows/image-build-source.yml
--- a/.github/workflows/image-build-source.yml
+++ b/.github/workflows/image-build-source.yml
@@ -59,120 +59,120 @@ jobs:
                     - x86-64
                     - arm64
         steps:
-            - name: (Build) Check Data
-              id: check_data
+            # - name: (Build) Check Data
+            #   id: check_data
+            #   shell: bash
+            #   run: |
+            #       exit 0
+            ## Checkout the code
+            - name: Checkout the latest code
+              id: git_checkout
+              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+
+            ## Set target env var based on the type of arch build
+            # ** we could move all later steps here, but it would be messier and and move verbose per arch.
+            - name: Configure Target Platform
+              id: configure_target_platform
               shell: bash
               run: |
+                  case ${{ matrix.cpu }} in
+                    x86-64*)
+                      ARCHIVE_NAME="$(echo "${{matrix.cpu}}" | sed -e 's|86-||g')" # if matrix.cpu ever changes to a different x86 version, this will set the archive naming appropriately.
+                      case ${{ matrix.cpu }} in
+                        x86-64)
+                          TARGET_CPU="${{ matrix.cpu }}-v3" # default to x86-64-v3 if generic x86-64 is used for the build
+                          ;;
+                        *)
+                          TARGET_CPU="${{ matrix.cpu }}" # if matrix.cpu is specifically v3/v4, we should target that
+                          ;;
+                      esac
+                      # install dependencies for linux x64 glibc and set target
+                      sudo apt-get update && sudo apt-get install -y git libclang-dev llvm || exit 1
+                      TARGET="x86_64-unknown-linux-gnu"
+                      ;;
+                    arm64)
+                      ARCHIVE_NAME=${{matrix.cpu}}
+                      # install dependencies for linux aarch64 glibc and set target
+                      sudo apt-get update && sudo apt-get install -y git gcc-aarch64-linux-gnu libclang-dev llvm || exit 1
+                      TARGET="aarch64-unknown-linux-gnu"
+                      ;;
+                    *)
+                      echo "Unsupporte arch ${{ matrix.cpu }}"
+                      exit 1
+                      ;;
+                  esac
+                  if [[ -z "$TARGET" ]]; then
+                    echo "[ERROR] TARGET Variable is empty for ${{ matrix.arch }}-${{ matrix.cpu }}";
+                    exit 1
+                  fi
+                  echo "setting TARGET:${TARGET}"
+                  echo "setting TARGET_CPU: ${TARGET_CPU}"
+                  echo "setting ZIPFILE_NAME: ${{ matrix.arch }}-${ARCHIVE_NAME}"
+                  echo "TARGET=${TARGET}" >> "$GITHUB_ENV"
+                  echo "TARGET_CPU=${TARGET_CPU}" >> "$GITHUB_ENV"
+                  echo "ZIPFILE_NAME=${{matrix.arch}}-${ARCHIVE_NAME}" >> "$GITHUB_ENV"
+
+            ## Install rust toolchain (llvm-tools-preview)
+            - name: Setup Rust Toolchain
+              id: setup_rust_toolchain
+              uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8 # v1.10.1
+              with:
+                  toolchain: stable
+                  cache: false
+                  target: ${{ env.TARGET }}
+
+            ## Build the release binaries
+            - name: Build Release
+              id: build_release
+              shell: bash
+              run: |
+                  echo "arch: ${{ matrix.arch }}"
+                  echo "cpu: ${{ matrix.cpu }}"
+                  echo "TARGET: ${{env.TARGET}}"
+                  echo "TARGET_CPU: ${{env.TARGET_CPU}}"
+                  echo "CMD: ${{env.CMD}}"
+                  echo "ZIPFILE_NAME: ${{env.ZIPFILE_NAME}}"
+
+                  case "${{env.TARGET}}" in
+                    # linux glibc aarch64
+                    aarch64-unknown-linux-gnu) # linux-glibc-arm64
+                      LINKER=aarch64-linux-gnu-gcc
+                      echo "$CMD --target $TARGET --config \"target.${TARGET}.linker=\\\"${LINKER}\\\"\" "
+                      ${{env.CMD}} --target $TARGET --config "target.${{env.TARGET}}.linker=\"${LINKER}\"" || exit 1
+                      ;;
+                    # linux glibc x64
+                    x86_64-unknown-linux-gnu) # linux-glibc-x86_64
+                       echo "$CMD --target $TARGET --config build.rustflags=\"\\\"-C target-cpu=${TARGET_CPU}\\\"\" "
+                      ${{env.CMD}} --target $TARGET --config build.rustflags="\"-C target-cpu=${TARGET_CPU}\"" || exit 1
+                      ;;
+                    *)
+                      echo "No matrix match for build target ($TARGET). using defaults"
+                      ${{env.CMD}} || exit 1
+                      ;;
+                  esac
                   exit 0
-            # ## Checkout the code
-            # - name: Checkout the latest code
-            #   id: git_checkout
-            #   uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
-            # ## Set target env var based on the type of arch build
-            # # ** we could move all later steps here, but it would be messier and and move verbose per arch.
-            # - name: Configure Target Platform
-            #   id: configure_target_platform
-            #   shell: bash
-            #   run: |
-            #       case ${{ matrix.cpu }} in
-            #         x86-64*)
-            #           ARCHIVE_NAME="$(echo "${{matrix.cpu}}" | sed -e 's|86-||g')" # if matrix.cpu ever changes to a different x86 version, this will set the archive naming appropriately.
-            #           case ${{ matrix.cpu }} in
-            #             x86-64)
-            #               TARGET_CPU="${{ matrix.cpu }}-v3" # default to x86-64-v3 if generic x86-64 is used for the build
-            #               ;;
-            #             *)
-            #               TARGET_CPU="${{ matrix.cpu }}" # if matrix.cpu is specifically v3/v4, we should target that
-            #               ;;
-            #           esac
-            #           # install dependencies for linux x64 glibc and set target
-            #           sudo apt-get update && sudo apt-get install -y git libclang-dev llvm || exit 1
-            #           TARGET="x86_64-unknown-linux-gnu"
-            #           ;;
-            #         arm64)
-            #           ARCHIVE_NAME=${{matrix.cpu}}
-            #           # install dependencies for linux aarch64 glibc and set target
-            #           sudo apt-get update && sudo apt-get install -y git gcc-aarch64-linux-gnu libclang-dev llvm || exit 1
-            #           TARGET="aarch64-unknown-linux-gnu"
-            #           ;;
-            #         *)
-            #           echo "Unsupporte arch ${{ matrix.cpu }}"
-            #           exit 1
-            #           ;;
-            #       esac
-            #       if [[ -z "$TARGET" ]]; then
-            #         echo "[ERROR] TARGET Variable is empty for ${{ matrix.arch }}-${{ matrix.cpu }}";
-            #         exit 1
-            #       fi
-            #       echo "setting TARGET:${TARGET}"
-            #       echo "setting TARGET_CPU: ${TARGET_CPU}"
-            #       echo "setting ZIPFILE_NAME: ${{ matrix.arch }}-${ARCHIVE_NAME}"
-            #       echo "TARGET=${TARGET}" >> "$GITHUB_ENV"
-            #       echo "TARGET_CPU=${TARGET_CPU}" >> "$GITHUB_ENV"
-            #       echo "ZIPFILE_NAME=${{matrix.arch}}-${ARCHIVE_NAME}" >> "$GITHUB_ENV"
+            ## Compress the binary artifact
+            - name: Compress binaries
+              id: compress_artifacts
+              shell: bash
+              run: |
+                  file -0 ./target/${{env.TARGET}}/release-lite/* | sed -nE 's/\x0:\s*(ELF|PE32+|Mach).*//p' | zip --junk-paths ${{env.ZIPFILE_NAME}}.zip -@
 
-            # ## Install rust toolchain (llvm-tools-preview)
-            # - name: Setup Rust Toolchain
-            #   id: setup_rust_toolchain
-            #   uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8 # v1.10.1
-            #   with:
-            #       toolchain: stable
-            #       cache: false
-            #       target: ${{ env.TARGET }}
+            ## Upload the binary artifact to the github action (used in `github-release.yml` to create a release)
+            - name: Upload Artifact
+              id: upload_artifact
+              uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
+              with:
+                  name: ${{ env.ZIPFILE_NAME }}
+                  # name: binaries-${{ env.ZIPFILE_NAME }}
+                  path: ${{ env.ZIPFILE_NAME }}.zip
 
-            # ## Build the release binaries
-            # - name: Build Release
-            #   id: build_release
-            #   shell: bash
-            #   run: |
-            #       echo "arch: ${{ matrix.arch }}"
-            #       echo "cpu: ${{ matrix.cpu }}"
-            #       echo "TARGET: ${{env.TARGET}}"
-            #       echo "TARGET_CPU: ${{env.TARGET_CPU}}"
-            #       echo "CMD: ${{env.CMD}}"
-            #       echo "ZIPFILE_NAME: ${{env.ZIPFILE_NAME}}"
-
-            #       case "${{env.TARGET}}" in
-            #         # linux glibc aarch64
-            #         aarch64-unknown-linux-gnu) # linux-glibc-arm64
-            #           LINKER=aarch64-linux-gnu-gcc
-            #           echo "$CMD --target $TARGET --config \"target.${TARGET}.linker=\\\"${LINKER}\\\"\" "
-            #           ${{env.CMD}} --target $TARGET --config "target.${{env.TARGET}}.linker=\"${LINKER}\"" || exit 1
-            #           ;;
-            #         # linux glibc x64
-            #         x86_64-unknown-linux-gnu) # linux-glibc-x86_64
-            #            echo "$CMD --target $TARGET --config build.rustflags=\"\\\"-C target-cpu=${TARGET_CPU}\\\"\" "
-            #           ${{env.CMD}} --target $TARGET --config build.rustflags="\"-C target-cpu=${TARGET_CPU}\"" || exit 1
-            #           ;;
-            #         *)
-            #           echo "No matrix match for build target ($TARGET). using defaults"
-            #           ${{env.CMD}} || exit 1
-            #           ;;
-            #       esac
-            #       exit 0
-
-            # ## Compress the binary artifact
-            # - name: Compress binaries
-            #   id: compress_artifacts
-            #   shell: bash
-            #   run: |
-            #       file -0 ./target/${{env.TARGET}}/release-lite/* | sed -nE 's/\x0:\s*(ELF|PE32+|Mach).*//p' | zip --junk-paths ${{env.ZIPFILE_NAME}}.zip -@
-
-            # ## Upload the binary artifact to the github action (used in `github-release.yml` to create a release)
-            # - name: Upload Artifact
-            #   id: upload_artifact
-            #   uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
-            #   with:
-            #       name: ${{ env.ZIPFILE_NAME }}
-            #       # name: binaries-${{ env.ZIPFILE_NAME }}
-            #       path: ${{ env.ZIPFILE_NAME }}.zip
-
-            # ## Attest the release binaries
-            # - name: Attest Release Artifact
-            #   uses: actions/attest-build-provenance@c074443f1aee8d4aeeae555aebba3282517141b2 #v2.2.3
-            #   with:
-            #       subject-path: ${{ env.ZIPFILE_NAME }}.zip
+            ## Attest the release binaries
+            - name: Attest Release Artifact
+              uses: actions/attest-build-provenance@c074443f1aee8d4aeeae555aebba3282517141b2 #v2.2.3
+              with:
+                  subject-path: ${{ env.ZIPFILE_NAME }}.zip
 
     image:
         name: Build Image
@@ -198,13 +198,13 @@ jobs:
                   echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV # from composite
                   echo "DOCKER_PUSH=$push" >> $GITHUB_ENV
 
-            # - name: Download Artifacts
-            #   id: download_artifacts
-            #   uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
-            #   with:
-            #       pattern: linux-glibc*
-            #       path: /tmp/release
-            #       merge-multiple: true
+            - name: Download Artifacts
+              id: download_artifacts
+              uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
+              with:
+                  pattern: linux-glibc*
+                  path: /tmp/release
+                  merge-multiple: true
 
             # ## Setup Docker for the builds
             # - name: Docker setup
@@ -257,6 +257,7 @@ jobs:
                   echo "platforms: ${{ env.docker_platforms }}"
                   echo "labels: ${{ steps.docker_metadata.outputs.labels }}"
                   echo "tags: ${{ steps.docker_metadata.outputs.tags }}"
+                  echo "push: ${{ env.DOCKER_PUSH }}"
                   echo "env.branch_name: ${{ env.BRANCH_NAME }}"
                   echo "github.repository: ${{ github.repository}}"
                   echo "github.repository_owner: ${{ github.repository_owner}}"
@@ -269,24 +270,23 @@ jobs:
                   echo "    GIT_BRANCH=${{ env.GITHUB_REF_SHORT }}"
                   echo "    GIT_COMMIT=${{ env.GITHUB_SHA_SHORT }}"
 
-            # - name: Build and Push ( ${{matrix.dist}} )
-            #   id: docker_build
-            #   uses: docker/build-push-action@ca877d9245402d1537745e0e356eab47c3520991 # v6.13.0
-            #   with:
-            #       context: /tmp
-            #       file: ./.github/actions/dockerfiles/${{ matrix.dist }}/Dockerfile.release
-            #       # file: ./.github/actions/dockerfiles/Dockerfile.${{ matrix.dist }}-binary
-            #       platforms: ${{ env.docker_platforms }}
-            #       tags: ${{ steps.docker_metadata.outputs.tags }}
-            #       labels: ${{ steps.docker_metadata.outputs.labels }}
-            #       push: ${{ env.DOCKER_PUSH }}
+            - name: Build and Push ( ${{matrix.dist}} )
+              id: docker_build
+              uses: docker/build-push-action@ca877d9245402d1537745e0e356eab47c3520991 # v6.13.0
+              with:
+                  context: /tmp
+                  file: ./.github/actions/dockerfiles/${{ matrix.dist }}/Dockerfile
+                  platforms: ${{ env.docker_platforms }}
+                  tags: ${{ steps.docker_metadata.outputs.tags }}
+                  labels: ${{ steps.docker_metadata.outputs.labels }}
+                  push: ${{ env.DOCKER_PUSH }}
 
-            # ## Generate docker image attestation(s)
-            # - name: Generate artifact attestation (${{ github.event.repository.name }})
-            #   id: attest_primary
-            #   uses: actions/attest-build-provenance@c074443f1aee8d4aeeae555aebba3282517141b2 # v2.2.3
-            #   with:
-            #       subject-name: |
-            #           ${{ env.docker_images }}
-            #       subject-digest: ${{ steps.docker_build.outputs.digest }}
-            #       push-to-registry: ${{ env.DOCKER_PUSH }}
+            ## Generate docker image attestation(s)
+            - name: Generate artifact attestation (${{ github.event.repository.name }})
+              id: attest_primary
+              uses: actions/attest-build-provenance@c074443f1aee8d4aeeae555aebba3282517141b2 # v2.2.3
+              with:
+                  subject-name: |
+                      ${{ env.docker_images }}
+                  subject-digest: ${{ steps.docker_build.outputs.digest }}
+                  push-to-registry: ${{ env.DOCKER_PUSH }}
