use artifacts for source build

diff --git a/.github/workflows/image-build-source.yml b/.github/workflows/image-build-source.yml
--- a/.github/workflows/image-build-source.yml
+++ b/.github/workflows/image-build-source.yml
@@ -3,90 +3,282 @@
 name: Docker Image (Source)
 
 on:
-  workflow_dispatch:
-  workflow_call:
+    workflow_dispatch:
+    workflow_call:
 
 ## Define which docker arch to build for
 env:
-  docker_platforms: "linux/amd64"
-  docker-org: blockstack
+    docker_platforms: "linux/amd64,linux/arm64"
+    docker-org: blockstack
 
 concurrency:
-  group: docker-image-source-${{ github.head_ref || github.ref || github.run_id }}
-  ## Always cancel duplicate jobs
-  cancel-in-progress: true
+    group: docker-image-source-${{ github.head_ref || github.ref || github.run_id }}
+    ## Always cancel duplicate jobs
+    cancel-in-progress: true
 
 jobs:
-  ## Runs anytime `ci.yml` runs or when manually called
-  image:
-    name: Build Image
-    runs-on: ubuntu-latest
-    ## Requires the repo environment "Push to Docker", which will trigger a secondary approval step before running this workflow.
-    environment: "Push to Docker"
-    permissions:
-      id-token: write
-      attestations: write
-    steps:
-      ## Setup Docker for the builds
-      - name: Docker setup
-        id: docker_setup
-        uses: stacks-network/actions/docker@main
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_PASSWORD }}
 
-      ## if the repo owner is not `stacks-network`, default to a docker-org of the repo owner (i.e. github user id)
-      ## this allows forks to run the docker push workflows without having to hardcode a dockerhub org (but it does require docker hub user to match github username)
-      - name: Set Local env vars
-        id: set_env
-        if: |
-          github.repository_owner != 'stacks-network'
-        run: |
-          echo "docker-org=${{ github.repository_owner }}" >> "$GITHUB_ENV"
+env:
+    # set a default command to build. we'll define specific build config options later per arch.
+    CMD: "cargo build --features monitoring_prom,slog_json --profile release-lite --workspace"
+    # ensure these env vars have no values since they will be explicitly set later
+    TARGET_CPU: ""
+    LINKER: ""
+jobs:
+    ## Build arch dependent binaries from source
+    build-binaries:
+        name: Build Binaries
+        runs-on: ubuntu-latest
+        permissions:
+            id-token: write
+            attestations: write
 
-      ## Set docker metatdata
-      - name: Docker Metadata ( ${{matrix.dist}} )
-        id: docker_metadata
-        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 #v5.6.1
-        with:
-          images: |
-            ${{env.docker-org}}/${{ github.event.repository.name }}
-            ${{env.docker-org}}/stacks-blockchain
-          tags: |
-            type=raw,value=${{ env.BRANCH_NAME }}
-            type=ref,event=pr
+        # needs:
+        #     - andon-cord
+        strategy:
+            ## Run a maximum of 10 builds concurrently, using the matrix defined in inputs.arch
+            max-parallel: 10
+            matrix:
+                arch:
+                    - linux-glibc
+                cpu:
+                    - x86-64
+                    - arm64
+                os:
+                    - ubuntu-latest
 
-      ## Build docker image
-      - name: Build and Push ( ${{matrix.dist}} )
-        id: docker_build
-        uses: docker/build-push-action@ca877d9245402d1537745e0e356eab47c3520991 # v6.13.0
-        with:
-          file: ./Dockerfile
-          platforms: ${{ env.docker_platforms }}
-          tags: ${{ steps.docker_metadata.outputs.tags }}
-          labels: ${{ steps.docker_metadata.outputs.labels }}
-          build-args: |
-            STACKS_NODE_VERSION=${{ env.GITHUB_SHA_SHORT }}
-            GIT_BRANCH=${{ env.GITHUB_REF_SHORT }}
-            GIT_COMMIT=${{ env.GITHUB_SHA_SHORT }}
-            TARGET_CPU=x86-64-v3
-          push: ${{ env.DOCKER_PUSH }}
+        steps:
+            # ## cleanup runner
+            # - name: Cleanup Runner
+            #   id: runner_cleanup
+            #   uses: stacks-network/actions/cleanup/disk@main
 
-      ## Generate docker image attestation(s)
-      - name: Generate artifact attestation (${{ github.event.repository.name }})
-        id: attest_primary
-        uses: actions/attest-build-provenance@c074443f1aee8d4aeeae555aebba3282517141b2 # v2.2.3
-        with:
-          subject-name: |
-            index.docker.io/${{env.docker-org}}/${{ github.event.repository.name }}
-          subject-digest: ${{ steps.docker_build.outputs.digest }}
-          push-to-registry: true
+            ## Checkout the code
+            - name: Checkout the latest code
+              id: git_checkout
+              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
-      - name: Generate artifact attestation (stacks-blockchain)
-        id: attest_secondary
-        uses: actions/attest-build-provenance@c074443f1aee8d4aeeae555aebba3282517141b2 # v2.2.3
-        with:
-          subject-name: |
-            index.docker.io/${{env.docker-org}}/stacks-blockchain
-          subject-digest: ${{ steps.docker_build.outputs.digest }}
-          push-to-registry: true
+            ## Set target env var based on the type of arch build
+            # ** we could move all later steps here, but it would be messier and and move verbose per arch.
+            - name: Configure Target Platform
+              id: configure_target_platform
+              shell: bash
+              run: |
+                  case ${{ matrix.cpu }} in
+                    x86-64*)
+                      ARCHIVE_NAME="$(echo "${{matrix.cpu}}" | sed -e 's|86-||g')" # if matrix.cpu ever changes to a different x86 version, this will set the archive naming appropriately.
+                      case ${{ matrix.cpu }} in
+                        x86-64)
+                          TARGET_CPU="${{ matrix.cpu }}-v3" # default to x86-64-v3 if generic x86-64 is used for the build
+                          ;;
+                        *)
+                          TARGET_CPU="${{ matrix.cpu }}" # if matrix.cpu is specifically v3/v4, we should target that
+                          ;;
+                      esac
+                      # install dependencies for linux x64 glibc and set target
+                      sudo apt-get install -y git libclang-dev llvm || exit 1
+                      TARGET="x86_64-unknown-linux-gnu"
+                      ;;
+                    arm64)
+                      ARCHIVE_NAME=${{matrix.cpu}}
+                      # install dependencies for linux aarch64 glibc and set target
+                      sudo apt-get install -y git gcc-aarch64-linux-gnu libclang-dev llvm || exit 1
+                      TARGET="aarch64-unknown-linux-gnu"
+                      ;;
+                      ;;
+                    *)
+                      echo "Unsupporte arch ${{ matrix.cpu }}"
+                      exit 1
+                      ;;
+                  esac
+                  if [[ -z "$TARGET" ]]; then
+                    echo "[ERROR] TARGET Variable is empty for ${{ matrix.arch }}-${{ matrix.cpu }}";
+                    exit 1
+                  fi
+                  echo "setting TARGET:${TARGET}"
+                  echo "setting TARGET_CPU: ${TARGET_CPU}"
+                  echo "setting ZIPFILE_NAME: ${{ matrix.arch }}-${ARCHIVE_NAME}"
+                  echo "TARGET=${TARGET}" >> "$GITHUB_ENV"
+                  echo "TARGET_CPU=${TARGET_CPU}" >> "$GITHUB_ENV"
+                  echo "ZIPFILE_NAME=${{matrix.arch}}-${ARCHIVE_NAME}" >> "$GITHUB_ENV"
+
+            ## Install rust toolchain (llvm-tools-preview)
+            - name: Setup Rust Toolchain
+              id: setup_rust_toolchain
+              uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8 # v1.10.1
+              with:
+                  toolchain: stable
+                  cache: false
+                  target: ${{ env.TARGET }}
+
+            ## Build the release binaries
+            - name: Build Release
+              id: build_release
+              shell: bash
+              run: |
+                  echo "arch: ${{ matrix.arch }}"
+                  echo "cpu: ${{ matrix.cpu }}"
+                  echo "os: ${{ matrix.os }}"
+                  echo "TARGET: ${{env.TARGET}}"
+                  echo "TARGET_CPU: ${{env.TARGET_CPU}}"
+                  echo "CMD: ${{env.CMD}}"
+                  echo "ZIPFILE_NAME: ${{env.ZIPFILE_NAME}}"
+
+                  case "${{env.TARGET}}" in
+                    # linux glibc aarch64
+                    aarch64-unknown-linux-gnu) # linux-glibc-arm64
+                      LINKER=aarch64-linux-gnu-gcc
+                      echo "$CMD --target $TARGET --config \"target.${TARGET}.linker=\\\"${LINKER}\\\"\" "
+                      ${{env.CMD}} --target $TARGET --config "target.${{env.TARGET}}.linker=\"${LINKER}\"" || exit 1
+                      ;;
+                    # linux glibc x64
+                    x86_64-unknown-linux-gnu) # linux-glibc-x86_64
+                       echo "$CMD --target $TARGET --config build.rustflags=\"\\\"-C target-cpu=${TARGET_CPU}\\\"\" "
+                      ${{env.CMD}} --target $TARGET --config build.rustflags="\"-C target-cpu=${TARGET_CPU}\"" || exit 1
+                      ;;
+                    *)
+                      echo "No matrix match for build target ($TARGET). using defaults"
+                      ${{env.CMD}} || exit 1
+                      ;;
+                  esac
+                  exit 0
+
+            ## Compress the binary artifact
+            - name: Compress binaries
+              id: compress_artifacts
+              shell: bash
+              run: |
+                  file -0 ./target/${{env.TARGET}}/release-lite/* | sed -nE 's/\x0:\s*(ELF|PE32+|Mach).*//p' | zip --junk-paths ${{env.ZIPFILE_NAME}}.zip -@
+
+            ## Upload the binary artifact to the github action (used in `github-release.yml` to create a release)
+            - name: Upload Artifact
+              id: upload_artifact
+              uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
+              with:
+                  name: ${{ env.ZIPFILE_NAME }}
+                  # name: binaries-${{ env.ZIPFILE_NAME }}
+                  path: ${{ env.ZIPFILE_NAME }}.zip
+
+            ## Attest the release binaries
+            - name: Attest Release Artifact
+              uses: actions/attest-build-provenance@c074443f1aee8d4aeeae555aebba3282517141b2 #v2.2.3
+              with:
+                  subject-path: ${{ env.ZIPFILE_NAME }}.zip
+
+    image:
+        name: Build Image
+        runs-on: ubuntu-latest
+        ## Requires the repo environment "Push to Docker", which will trigger a secondary approval step before running this workflow.
+        environment: "Push to Docker"
+        needs:
+          - build-binaries
+        permissions:
+            id-token: write
+            attestations: write
+        steps:
+            - name: Download Artifacts
+              id: download_artifacts
+              uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
+              with:
+                  # pattern: binaries-*
+                  pattern: linux-glibc*
+                  path: /tmp/release
+                  merge-multiple: true
+
+            - name: Check Data
+              id: check_data
+              shell: bash
+              run: |
+                  echo "pwd:"
+                  pwd
+                  echo "checking release dir:"
+                  ls -al /tmp/release
+                  echo "tag: ${{ env.tag}}"
+                  echo "docker_tag: ${{ env.docker_tag }}"
+                  echo "docker_tag_rc: ${{ env.docker_tag_rc }}"
+                  echo "docker_org: ${{ env.docker_org }}"
+
+            ## Setup Docker for the builds
+            - name: Docker setup
+              id: docker_setup
+              uses: stacks-network/actions/docker@main
+              with:
+                  username: ${{ secrets.DOCKERHUB_USERNAME }}
+                  password: ${{ secrets.DOCKERHUB_PASSWORD }}
+
+            ## if the repo owner is not `stacks-network`, default to a docker-org of the repo owner (i.e. github user id)
+            ## this allows forks to run the docker push workflows without having to hardcode a dockerhub org (but it does require docker hub user to match github username)
+            - name: Set Local env vars
+              id: set_env
+              if: |
+                  github.repository_owner != 'stacks-network'
+              run: |
+                  echo "docker-org=${{ github.repository_owner }}" >> "$GITHUB_ENV"
+
+            ## Set docker metatdata
+            - name: Docker Metadata ( ${{matrix.dist}} )
+              id: docker_metadata
+              uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 #v5.6.1
+              with:
+                  images: |
+                      ${{env.docker-org}}/${{ github.event.repository.name }}
+                      ${{env.docker-org}}/stacks-blockchain
+                  tags: |
+                      type=raw,value=${{ env.BRANCH_NAME }}
+                      type=ref,event=pr
+
+            ## Build docker image for node release
+            - name: Show vals ( ${{matrix.dist}} )
+              if: ${{ env.is-signer-release == 'false' }}
+              id: show_vals
+              shell: bash
+              run: |
+                  echo "platforms: ${{ env.platforms }}"
+                  echo "labels: ${{ steps.docker_metadata.outputs.labels }}"
+                  echo "docker_tag: ${{ env.docker_tag }}"
+                  echo "tag: ${{ env.tag }}"
+                  echo
+                  echo "build args:"
+                  echo "    TAG=$${{ steps.docker_metadata.outputs.tags }}"
+                  echo "    REPO=${{ github.repository_owner }}/${{ github.event.repository.name }}"
+                  echo "    STACKS_NODE_VERSION=${{ env.tag || env.GITHUB_SHA_SHORT }}"
+                  echo "    GIT_BRANCH=${{ env.GITHUB_REF_SHORT }}"
+                  echo "    GIT_COMMIT=${{ env.GITHUB_SHA_SHORT }}"
+                  echo "push: ${{ env.DOCKER_PUSH }}"
+
+            - name: Build and Push ( ${{matrix.dist}} )
+              if: ${{ env.is-signer-release == 'false' }}
+              id: docker_build_node
+              uses: docker/build-push-action@ca877d9245402d1537745e0e356eab47c3520991 # v6.13.0
+              with:
+                  context: /tmp
+                  file: ./.github/actions/dockerfiles/Dockerfile.${{ matrix.dist }}-binary
+                  platforms: ${{ env.platforms }}
+                  tags: ${{ steps.docker_metadata.outputs.tags }}
+                  labels: ${{ steps.docker_metadata.outputs.labels }}
+                  build-args: |
+                      TAG=${{ steps.docker_metadata.outputs.tags }}
+                      REPO=${{ github.repository_owner }}/${{ github.event.repository.name }}
+                      STACKS_NODE_VERSION=${{ env.tag || env.GITHUB_SHA_SHORT }}
+                      GIT_BRANCH=${{ env.GITHUB_REF_SHORT }}
+                      GIT_COMMIT=${{ env.GITHUB_SHA_SHORT }}
+                  push: ${{ env.DOCKER_PUSH }}
+
+            ## Generate docker image attestation(s)
+            - name: Generate artifact attestation (${{ github.event.repository.name }})
+              id: attest_primary
+              uses: actions/attest-build-provenance@c074443f1aee8d4aeeae555aebba3282517141b2 # v2.2.3
+              with:
+                  subject-name: |
+                      index.docker.io/${{env.docker-org}}/${{ github.event.repository.name }}
+                  subject-digest: ${{ steps.docker_build.outputs.digest }}
+                  push-to-registry: true
+
+            - name: Generate artifact attestation (stacks-blockchain)
+              id: attest_secondary
+              uses: actions/attest-build-provenance@c074443f1aee8d4aeeae555aebba3282517141b2 # v2.2.3
+              with:
+                  subject-name: |
+                      index.docker.io/${{env.docker-org}}/stacks-blockchain
+                  subject-digest: ${{ steps.docker_build.outputs.digest }}
+                  push-to-registry: true
