adsf

diff --git a/.github/workflows/slow-tests.yml b/.github/workflows/slow-tests.yml
--- a/.github/workflows/slow-tests.yml
+++ b/.github/workflows/slow-tests.yml
@@ -74,50 +74,94 @@ jobs:
     steps:
       - name: Checkout the latest code
         id: git_checkout
-        run: |
-          echo "Checkout the latest code"
+        uses: actions/checkout@v3
 
       - name: Setup Rust Toolchain
         id: setup_rust_toolchain
-        run: |
-          echo "Setup Rust Toolchain"
+        uses: actions-rust-lang/setup-rust-toolchain@v1
+        with:
+          toolchain: stable
+          components: llvm-tools-preview
+          cache: false
 
       - name: Restore Cargo Cache
         id: restore_cargo_cache
-        run: |
-          echo "Restore Cargo Cache"
+        uses: actions/cache/restore@v3
+        with:
+          fail-on-cache-miss: true
+          path: |
+            ~/.cargo/bin/
+            ~/.cargo/registry/index/
+            ~/.cargo/registry/cache/
+            ~/.cargo/git/db/
+          key: ${{ github.event.repository.name }}-cargo
+          # key: ${{ github.event.repository.name }}-${{ github.sha }}-cargo
 
       - name: Restore Bitcoin Binary Cache
         id: restore_bitcoin_cache
-        run: |
-          echo "Restore Bitcoin Binary Cache"
+        uses: actions/cache/restore@v3
+        with:
+          fail-on-cache-miss: true
+          path: /tmp/bitcoin
+          key: ${{ github.event.repository.name }}-bitcoin-binaries
 
       - name: Restore Test Archive Cache
         id: restore_test-archive_cache
-        run: |
-          echo "Restore Test Archive Cache"
+        uses: actions/cache/restore@v3
+        with:
+          fail-on-cache-miss: true
+          path: /tmp/test_archive.tar.zst
+          key: ${{ github.event.repository.name }}-test-archive
+          # key: ${{ github.event.repository.name }}-${{ github.sha }}-test-archive
 
       - name: Restore Target Cache
         id: restore_target_cache
-        run: |
-          echo "Restore Target Cache"
+        uses: actions/cache/restore@v3
+        with:
+          fail-on-cache-miss: true
+          path: ./target
+          key: ${{ github.event.repository.name }}-target
+          # key: ${{ github.event.repository.name }}-${{ github.sha }}-target
 
       - name: Link Bitcoin Binary
         id: bitcoin_binary
         run: |
-          echo "Link Bitcoin Binary"
+          sudo ln -s /tmp/bitcoin/bin/bitcoind /bin/
+          ls -al /bin/bitcoind
 
       - name: Run Tests
         id: run_tests
         run: |
-          echo "Run Test: ${{ matrix.test-name }}"
+          cargo nextest run \
+            --test-threads 1 \
+            --run-ignored all \
+            --retries 2 \
+            --final-status-level fail \
+            --archive-file /tmp/test_archive.tar.zst \
+            "${{ matrix.test-name }}"
 
       - name: Run grcov
         id: run_grcov
         run: |
-          echo "Run grcov"
+          grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info || exit 1
+
+      # - name: Code Coverage
+      #   id: code_coverage
+      #   uses: codecov/codecov-action@v3
+      #   with:
+      #     files: ./lcov.info
+      #     name: ${{ matrix.test-name }}
+      #     fail_ci_if_error: false
 
       - name: Upload Code Coverage
         id: code_coverage
-        run: |
-          echo "Upload Code Coverage"
+        uses: Wandalen/wretry.action@master
+        with:
+          action: codecov/codecov-action@v3
+          with: |
+            files: ./lcov.info
+            name: ${{ matrix.test-name }}
+            fail_ci_if_error: false
+            verbose: true
+          attempt_limit: 3
+          attempt_delay: 10000
diff --git a/.github/workflows/stacks-blockchain-tests.yml b/.github/workflows/stacks-blockchain-tests.yml
--- a/.github/workflows/stacks-blockchain-tests.yml
+++ b/.github/workflows/stacks-blockchain-tests.yml
@@ -38,39 +38,11 @@ concurrency:
   cancel-in-progress: ${{ github.event_name == 'pull_request' }}
 
 jobs:
-  # check-cache:
-  #   # if: ${{ false }}
-  #   name: Check Cache
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Check Bitcoin Cache
-  #       # uses: buildjet/cache@v3
-  #       uses: actions/cache@v3
-  #       id: check_cache
-  #       with:
-  #         lookup-only: true
-  #         path: /tmp/bitcoin
-  #         key: ${{ github.event.repository.name }}-bitcoin-binaries
-
-  #     - name: Check Target Cache
-  #       # uses: buildjet/cache@v3
-  #       uses: actions/cache@v3
-  #       id: check_target_cache
-  #       with:
-  #         lookup-only: true
-  #         # path: ./target/debug
-  #         # key: ${{ github.event.repository.name }}-target-debug
-  #         # # key: ${{ github.event.repository.name }}-${{ github.sha }}-target-debug
-  #         path: ./target
-  #         key: ${{ github.event.repository.name }}-target
-
   # full genesis test with code coverage
   full-genesis:
     # if: ${{ false }}
     name: Full Genesis Test
     runs-on: ubuntu-latest
-    # needs:
-    #   - check-cache
     strategy:
       fail-fast: false
       max-parallel: 2
@@ -80,111 +52,190 @@ jobs:
     steps:
       - name: Checkout the latest code
         id: git_checkout
-        run: |
-          echo "Checkout the latest code"
+        uses: actions/checkout@v3
 
       - name: Setup Rust Toolchain
         id: setup_rust_toolchain
-        run: |
-          echo "Setup Rust Toolchain"
+        uses: actions-rust-lang/setup-rust-toolchain@v1
+        with:
+          toolchain: stable
+          components: llvm-tools-preview
+          cache: false
 
       - name: Restore Cargo Cache
         id: restore_cargo_cache
-        run: |
-          echo "Restore Cargo Cache"
+        uses: actions/cache/restore@v3
+        with:
+          fail-on-cache-miss: true
+          path: |
+            ~/.cargo/bin/
+            ~/.cargo/registry/index/
+            ~/.cargo/registry/cache/
+            ~/.cargo/git/db/
+          key: ${{ github.event.repository.name }}-cargo
+          # key: ${{ github.event.repository.name }}-${{ github.sha }}-cargo
 
       - name: Restore Bitcoin Binary Cache
         id: restore_bitcoin_cache
-        run: |
-          echo "Restore Bitcoin Binary Cache"
+        uses: actions/cache/restore@v3
+        with:
+          fail-on-cache-miss: true
+          path: /tmp/bitcoin
+          key: ${{ github.event.repository.name }}-bitcoin-binaries
 
       - name: Restore Genesis Archive Cache
         id: restore_test-archive_cache
-        run: |
-          echo "Restore Genesis Archive Cache"
+        uses: actions/cache/restore@v3
+        with:
+          fail-on-cache-miss: true
+          path: /tmp/genesis_archive.tar.zst
+          key: ${{ github.event.repository.name }}-genesis-archive
+          # key: ${{ github.event.repository.name }}-${{ github.sha }}-genesis-archive
 
       - name: Restore Target Cache
         id: restore_target_cache
-        run: |
-          echo "Restore Target Cache"
+        uses: actions/cache/restore@v3
+        with:
+          fail-on-cache-miss: true
+          path: ./target
+          key: ${{ github.event.repository.name }}-target
+          # key: ${{ github.event.repository.name }}-${{ github.sha }}-target
 
       - name: Link Bitcoin Binary
         id: bitcoin_binary
         run: |
-          echo "Link Bitcoin Binary"
+          sudo ln -s /tmp/bitcoin/bin/bitcoind /bin/
+          ls -al /bin/bitcoind
 
       - name: Run Tests
         id: run_tests
         run: |
-          echo "Run Test ${{ matrix.test-name }}"
+          cargo nextest run \
+            --test-threads 1 \
+            --run-ignored all \
+            --retries 2 \
+            --final-status-level fail \
+            --archive-file /tmp/genesis_archive.tar.zst \
+            "${{ matrix.test-name }}"
 
       - name: Run grcov
         id: run_grcov
         run: |
-          echo " Run grcov"
+          grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
 
       - name: Large Genesis Codecov
         id: full_genesis_codecov
-        run: |
-          echo "Large Genesis Codecov"
+        uses: codecov/codecov-action@v3
+        with:
+          files: ./lcov.info
+          name: large_genesis
+          fail_ci_if_error: true
 
   # unit tests with code coverage
   unit-tests:
     # if: ${{ false }}
     name: Unit Tests
     runs-on: ubuntu-latest
-    # needs:
-    #   - check-cache
     steps:
       - name: Checkout the latest code
         id: git_checkout
-        run: |
-          echo "Checkout the latest code"
+        uses: actions/checkout@v3
 
       - name: Setup Rust Toolchain
         id: setup_rust_toolchain
-        run: |
-          echo "Setup Rust Toolchain"
+        uses: actions-rust-lang/setup-rust-toolchain@v1
+        with:
+          toolchain: stable
+          components: llvm-tools-preview
+          cache: false
 
       - name: Restore Cargo Cache
         id: restore_cargo_cache
-        run: |
-          echo "Restore Cargo Cache"
+        uses: actions/cache/restore@v3
+        with:
+          fail-on-cache-miss: true
+          path: |
+            ~/.cargo/bin/
+            ~/.cargo/registry/index/
+            ~/.cargo/registry/cache/
+            ~/.cargo/git/db/
+          key: ${{ github.event.repository.name }}-cargo
+          # key: ${{ github.event.repository.name }}-${{ github.sha }}-cargo
 
       - name: Restore Bitcoin Binary Cache
         id: restore_bitcoin_cache
-        run: |
-          echo "Restore Bitcoin Binary Cache"
+        uses: actions/cache/restore@v3
+        with:
+          fail-on-cache-miss: true
+          path: /tmp/bitcoin
+          key: ${{ github.event.repository.name }}-bitcoin-binaries
 
       - name: Restore Test Archive Cache
         id: restore_test-archive_cache
-        run: |
-          echo "Restore Test Archive Cache"
+        uses: actions/cache/restore@v3
+        with:
+          fail-on-cache-miss: true
+          path: /tmp/test_archive.tar.zst
+          key: ${{ github.event.repository.name }}-test-archive
+          # key: ${{ github.event.repository.name }}-${{ github.sha }}-test-archive
 
       - name: Restore Target Cache
         id: restore_target_cache
-        run: |
-          echo "Restore Target Cache"
+        uses: actions/cache/restore@v3
+        with:
+          fail-on-cache-miss: true
+          path: ./target
+          key: ${{ github.event.repository.name }}-target
+          # key: ${{ github.event.repository.name }}-${{ github.sha }}-target
 
       - name: Link Bitcoin Binary
         id: bitcoin_binary
         run: |
-          echo "Link Bitcoin Binary"
+          sudo ln -s /tmp/bitcoin/bin/bitcoind /bin/
+          ls -al /bin/bitcoind
 
       - name: Run Tests
         id: run_tests
         run: |
-          echo "Run Test ${{ matrix.test-name }}"
+          cargo nextest run \
+            --test-threads num-cpus \
+            --retries 2 \
+            --final-status-level fail \
+            --archive-file /tmp/test_archive.tar.zst
+
+          # cargo nextest run \
+          #   --test-threads num-cpus \
+          #   --run-ignored all \
+          #   --archive-file /tmp/test_archive.tar.zst \
+          #   --retries 2 \
+          #   --final-status-level fail \
+          #   neon_integrations::bitcoind_integration_test
 
       - name: Run grcov
         id: run_grcov
         run: |
-          echo "Run grcov"
+          grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
+
+      # - name: Unit Test Codecov
+      #   id: codedov
+      #   uses: codecov/codecov-action@v3
+      #   with:
+      #     files: ./lcov.info
+      #     name: unit_tests
+      #     fail_ci_if_error: true
 
       - name: Upload Code Coverage
         id: code_coverage
-        run: |
-          echo "Upload Code Coverage"
+        uses: Wandalen/wretry.action@master
+        with:
+          action: codecov/codecov-action@v3
+          with: |
+            files: ./lcov.info
+            name: unit_tests
+            fail_ci_if_error: false
+            verbose: true
+          attempt_limit: 3
+          attempt_delay: 10000
 
   open-api-validation:
     # if: ${{ false }}
@@ -193,23 +244,26 @@ jobs:
     steps:
       - name: Checkout the latest code
         id: git_checkout
-        run: |
-          echo "Checkout the latest code"
+        uses: actions/checkout@v3
 
       - name: Redoc
         id: run_redoc
-        run: |
-          echo "Redoc"
+        uses: seeebiii/redoc-cli-github-action@v10
+        with:
+          args: "bundle -o ./open-api-docs.html ./docs/rpc/openapi.yaml"
 
       - name: check result
         id: check_redoc
         run: |
-          echo "check result"
+          test -f ./open-api-docs.html || (echo "Missing ./open-api-docs.html from previous step." && exit 1)
 
       - name: Upload bundled html
         id: upload_html_artifact
-        run: |
-          echo "Upload bundled html"
+        uses: actions/upload-artifact@v3
+        with:
+          name: open-api-bundle
+          path: |
+            ./open-api-docs.html
 
   # Disabled :: net-tests
   nettest:
@@ -222,13 +276,13 @@ jobs:
     steps:
       - name: Checkout the latest code
         id: git_checkout
-        run: |
-          echo "Checkout the latest code"
+        uses: actions/checkout@v3
 
       - name: Run network relay tests
         id: nettest
-        run: |
-          echo "Run network relay tests"
+        env:
+          DOCKER_BUILDKIT: 1
+        run: docker build -f ./.github/actions/bitcoin-int-tests/Dockerfile.net-tests .
 
   # Core contract tests
   core-contracts-clarinet-test:
@@ -237,15 +291,17 @@ jobs:
     steps:
       - name: Checkout the latest code
         id: git_checkout
-        run: |
-          echo "Checkout the latest code"
+        uses: actions/checkout@v3
 
       - name: Execute core contract unit tests in Clarinet
         id: clarinet_unit_test
-        run: |
-          echo "Execute core contract unit tests in Clarinet"
+        uses: docker://hirosystems/clarinet:latest
+        with:
+          args: test --coverage --manifest-path=./contrib/core-contract-tests/Clarinet.toml
 
       - name: Export code coverage
         id: clarinet_codecov
-        run: |
-          echo "Export code coverage"
+        uses: codecov/codecov-action@v3
+        with:
+          files: ./coverage.lcov
+          verbose: true
