timing test

diff --git a/.github/workflows/stacks-blockchain-tests.yml b/.github/workflows/stacks-blockchain-tests.yml
--- a/.github/workflows/stacks-blockchain-tests.yml
+++ b/.github/workflows/stacks-blockchain-tests.yml
@@ -38,19 +38,19 @@ concurrency:
   cancel-in-progress: ${{ github.event_name == 'pull_request' }}
 
 jobs:
-  # # check to see if cache exists, if not then recreate it
-  # create-cache:
-  #   name: Create Test Cache
-  #   uses: ./.github/workflows/create-cache.yml
-  #   # uses: wileyj/stacks-blockchain/.github/workflows/create_cache.yml@master
+  # check to see if cache exists, if not then recreate it
+  create-cache:
+    name: Create Test Cache
+    uses: ./.github/workflows/create-cache.yml
+    # uses: wileyj/stacks-blockchain/.github/workflows/create_cache.yml@master
 
   # full genesis test with code coverage
   full-genesis:
     # if: ${{ false }}
     name: Full Genesis Test
     runs-on: ubuntu-latest
-    # needs:
-    #   - create-cache
+    needs:
+      - create-cache
     strategy:
       fail-fast: false
       max-parallel: 2
@@ -58,30 +58,222 @@ jobs:
         test-name:
           - neon_integrations::bitcoind_integration_test
     steps:
-      - name: echo
+      - name: Checkout the latest code
+        id: git_checkout
+        uses: actions/checkout@v3
+
+      - name: Setup Rust Toolchain
+        id: setup_rust_toolchain
+        uses: actions-rust-lang/setup-rust-toolchain@v1
+        with:
+          toolchain: stable
+          components: llvm-tools-preview
+          cache: false
+
+      - name: Restore Cargo Cache
+        id: restore_cargo_cache
+        uses: actions/cache/restore@v3
+        with:
+          fail-on-cache-miss: true
+          path: |
+            ~/.cargo/bin/
+            ~/.cargo/registry/index/
+            ~/.cargo/registry/cache/
+            ~/.cargo/git/db/
+          key: ${{ github.event.repository.name }}-cargo
+          # key: ${{ github.event.repository.name }}-${{ github.sha }}-cargo
+
+      - name: Restore Bitcoin Binary Cache
+        id: restore_bitcoin_cache
+        uses: actions/cache/restore@v3
+        with:
+          fail-on-cache-miss: true
+          path: /tmp/bitcoin
+          key: ${{ github.event.repository.name }}-bitcoin-binaries
+
+      - name: Restore Genesis Archive Cache
+        id: restore_test-archive_cache
+        uses: actions/cache/restore@v3
+        with:
+          fail-on-cache-miss: true
+          path: /tmp/genesis_archive.tar.zst
+          key: ${{ github.event.repository.name }}-genesis-archive
+          # key: ${{ github.event.repository.name }}-${{ github.sha }}-genesis-archive
+
+      - name: Restore Target Cache
+        id: restore_target_cache
+        uses: actions/cache/restore@v3
+        with:
+          fail-on-cache-miss: true
+          path: ./target
+          key: ${{ github.event.repository.name }}-target
+          # key: ${{ github.event.repository.name }}-${{ github.sha }}-target
+
+      - name: Link Bitcoin Binary
+        id: bitcoin_binary
         run: |
-          echo "full-genesis"
+          sudo ln -s /tmp/bitcoin/bin/bitcoind /bin/
+          ls -al /bin/bitcoind
+
+      - name: Run Tests
+        id: run_tests
+        run: |
+          cargo nextest run \
+            --test-threads 1 \
+            --run-ignored all \
+            --retries 2 \
+            --final-status-level fail \
+            --archive-file /tmp/genesis_archive.tar.zst \
+            "${{ matrix.test-name }}"
+
+      - name: Run grcov
+        id: run_grcov
+        run: |
+          grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
+
+      - name: Large Genesis Codecov
+        id: full_genesis_codecov
+        uses: codecov/codecov-action@v3
+        with:
+          files: ./lcov.info
+          name: large_genesis
+          fail_ci_if_error: true
 
   # unit tests with code coverage
   unit-tests:
     # if: ${{ false }}
     name: Unit Tests
     runs-on: ubuntu-latest
-    # needs:
-    #   - create-cache
+    needs:
+      - create-cache
     steps:
-      - name: echo
+      - name: Checkout the latest code
+        id: git_checkout
+        uses: actions/checkout@v3
+
+      - name: Setup Rust Toolchain
+        id: setup_rust_toolchain
+        uses: actions-rust-lang/setup-rust-toolchain@v1
+        with:
+          toolchain: stable
+          components: llvm-tools-preview
+          cache: false
+
+      - name: Restore Cargo Cache
+        id: restore_cargo_cache
+        uses: actions/cache/restore@v3
+        with:
+          fail-on-cache-miss: true
+          path: |
+            ~/.cargo/bin/
+            ~/.cargo/registry/index/
+            ~/.cargo/registry/cache/
+            ~/.cargo/git/db/
+          key: ${{ github.event.repository.name }}-cargo
+          # key: ${{ github.event.repository.name }}-${{ github.sha }}-cargo
+
+      - name: Restore Bitcoin Binary Cache
+        id: restore_bitcoin_cache
+        uses: actions/cache/restore@v3
+        with:
+          fail-on-cache-miss: true
+          path: /tmp/bitcoin
+          key: ${{ github.event.repository.name }}-bitcoin-binaries
+
+      - name: Restore Test Archive Cache
+        id: restore_test-archive_cache
+        uses: actions/cache/restore@v3
+        with:
+          fail-on-cache-miss: true
+          path: /tmp/test_archive.tar.zst
+          key: ${{ github.event.repository.name }}-test-archive
+          # key: ${{ github.event.repository.name }}-${{ github.sha }}-test-archive
+
+      - name: Restore Target Cache
+        id: restore_target_cache
+        uses: actions/cache/restore@v3
+        with:
+          fail-on-cache-miss: true
+          path: ./target
+          key: ${{ github.event.repository.name }}-target
+          # key: ${{ github.event.repository.name }}-${{ github.sha }}-target
+
+      - name: Link Bitcoin Binary
+        id: bitcoin_binary
         run: |
-          echo "unit-tests"
+          sudo ln -s /tmp/bitcoin/bin/bitcoind /bin/
+          ls -al /bin/bitcoind
+
+      - name: Run Tests
+        id: run_tests
+        run: |
+          cargo nextest run \
+            --test-threads num-cpus \
+            --retries 2 \
+            --final-status-level fail \
+            --archive-file /tmp/test_archive.tar.zst
+
+          # cargo nextest run \
+          #   --test-threads num-cpus \
+          #   --run-ignored all \
+          #   --archive-file /tmp/test_archive.tar.zst \
+          #   --retries 2 \
+          #   --final-status-level fail \
+          #   neon_integrations::bitcoind_integration_test
+
+      - name: Run grcov
+        id: run_grcov
+        run: |
+          grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
+
+      # - name: Unit Test Codecov
+      #   id: codedov
+      #   uses: codecov/codecov-action@v3
+      #   with:
+      #     files: ./lcov.info
+      #     name: unit_tests
+      #     fail_ci_if_error: true
+
+      - name: Upload Code Coverage
+        id: code_coverage
+        uses: Wandalen/wretry.action@master
+        with:
+          action: codecov/codecov-action@v3
+          with: |
+            files: ./lcov.info
+            name: unit_tests
+            fail_ci_if_error: false
+            verbose: true
+          attempt_limit: 3
+          attempt_delay: 10000
 
   open-api-validation:
     # if: ${{ false }}
     name: OpenAPI Validation
     runs-on: ubuntu-latest
     steps:
-      - name: echo
+      - name: Checkout the latest code
+        id: git_checkout
+        uses: actions/checkout@v3
+
+      - name: Redoc
+        id: run_redoc
+        uses: seeebiii/redoc-cli-github-action@v10
+        with:
+          args: "bundle -o ./open-api-docs.html ./docs/rpc/openapi.yaml"
+
+      - name: check result
+        id: check_redoc
         run: |
-          echo "open-api-validation"
+          test -f ./open-api-docs.html || (echo "Missing ./open-api-docs.html from previous step." && exit 1)
+
+      - name: Upload bundled html
+        id: upload_html_artifact
+        uses: actions/upload-artifact@v3
+        with:
+          name: open-api-bundle
+          path: |
+            ./open-api-docs.html
 
   # Disabled :: net-tests
   nettest:
@@ -92,15 +284,34 @@ jobs:
     runs-on: ubuntu-latest
     # runs-on: buildjet-4vcpu-ubuntu-2204
     steps:
-      - name: echo
-        run: |
-          echo "nettest"
+      - name: Checkout the latest code
+        id: git_checkout
+        uses: actions/checkout@v3
+
+      - name: Run network relay tests
+        id: nettest
+        env:
+          DOCKER_BUILDKIT: 1
+        run: docker build -f ./.github/actions/bitcoin-int-tests/Dockerfile.net-tests .
 
   # Core contract tests
   core-contracts-clarinet-test:
     name: Core Contracts Test
     runs-on: ubuntu-latest
     steps:
-      - name: echo
-        run: |
-          echo "core-contracts-clarinet-test"
+      - name: Checkout the latest code
+        id: git_checkout
+        uses: actions/checkout@v3
+
+      - name: Execute core contract unit tests in Clarinet
+        id: clarinet_unit_test
+        uses: docker://hirosystems/clarinet:latest
+        with:
+          args: test --coverage --manifest-path=./contrib/core-contract-tests/Clarinet.toml
+
+      - name: Export code coverage
+        id: clarinet_codecov
+        uses: codecov/codecov-action@v3
+        with:
+          files: ./coverage.lcov
+          verbose: true
